# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUBLISHER_DZ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
