# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-14 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PUBLISHER_DZ', '0002_post_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
