# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUBLISHER_DZ', '0005_auto_20170214_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='e_mail',
            field=models.EmailField(max_length=50),
        ),
    ]
